config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/destroy'
  get 'order_items/update'
  get 'carts/show'
  root "client#index"
  get "login" => "sessions#new"
  get "signup" => "users#new"
  get "admin" => "users#index"
  post   'login'   => 'sessions#create'
  post 'comments' => "client#comment"  
  delete 'logout'  => 'sessions#destroy'
  get "search" => "client#search" , as: 'search'
  post "search" => "client#search" 
  get "products" => "products#index"
  get "details/:id" => "client#details" , as: "details"
  get "category/:id" => "client#category" , as: "category"
  resources :users
  resources :products
  resources :categories
  get "cart" => "carts#show"
  resources :order_items
end

app/views/admin/_header.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#"><span>TESTING </span>Admin</a>
            <ul class="user-menu">
                <li class="dropdown pull-right">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><svg class="glyph stroked male-user"><use xlink:href="#stroked-male-user"></use></svg> <%= current_user.name%><span class="caret"></span></a>
                    <ul class="dropdown-menu" role="menu">
                    <li><%= link_to "Log out", logout_path, method: "delete" %></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div><!-- /.container-fluid -->
</nav>

app/views/admin/_sidebar.html.erb
<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
    <form role="search">
    </form>
    <ul class="nav menu">
        <li><%=  link_to "Products", products_path %></li>
        <li><%= link_to "Users", users_path %> </li>
    
    </ul>

</div>