config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/destroy'
  get 'order_items/update'
  get 'carts/show'
  root "client#index"
  get "login" => "sessions#new"
  get "signup" => "users#new"
  get "admin" => "users#index"
  post   'login'   => 'sessions#create'
  post 'comments' => "client#comment"  
  delete 'logout'  => 'sessions#destroy'
  get "search" => "client#search" , as: 'search'
  post "search" => "client#search" 
  get "products" => "products#index"
  get "details/:id" => "client#details" , as: "details"
  get "category/:id" => "client#category" , as: "category"
  resources :users
  resources :products
  resources :categories
  get "cart" => "carts#show"
  resources :order_items
end

app/controllers/client_controller.rb
class ClientController < ApplicationController
  
    def index
        @products =  Product.all
        @categories = Category.all
        @products1 = @products.where(:prd_featured => true).order(id: :desc).limit(6)
        @products2 = @products.where(:prd_featured => false).order(id: :desc).limit(6)
    end
    
    def category 
        @category = Category.find(params[:id])
        @categories = Category.all
        @products = Product.where(:category_id => params[:id])
    end
      
    def details 
        @order_item = current_order.order_items.new
        @comments = Comment.where(:product_id => params[:id])
        @categories = Category.all
        @product =  Product.find(params[:id])
        @comment = Comment.new
    end

    def comment 
        @categories = Category.all

        @order_item = current_order.order_items.new
        @comment = Comment.new(comment_params)
        @product =  Product.find(@comment.product_id)
        @comments = Comment.where(:product_id => @comment.product_id)

        if @comment.save
            redirect_to details_path(@comment.product_id)
        else 
            render 'details'
        end
    end

    def search
        @categories = Category.all
        if params[:search].blank?  
            redirect_to(root_url, alert: "Empty field!")  
          else  
            @parameter = params[:search].downcase  
            @products = Product.all.where("prd_name LIKE ?", "%#{@parameter}%")  
          end  
    end


    private
        
        def comment_params
            params.require(:comment).permit(:product_id ,:name, :mail , :details)
        end

end

app/helpers/client_helper.rb
module ClientHelper
end

app/views/client/_categories.html.erb
<div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <nav>
            <div id="menu" class="collapse navbar-collapse">
                <ul>
                    <% @categories.each do |category| %>
                        <li class="menu-item"><%= link_to category.name , category_path(category.id) %></li>
                    <% end %>
                    
                </ul>
            </div>
        </nav>
    </div>
</div>

app/views/client/_footer.html.erb
<div id="footer-top">
	<div class="container">
    	<div class="row">
        	<div id="logo-2" class="col-lg-3 col-md-6 col-sm-12">
            	<h2><a href="#"><%= image_tag "logo-footer.png" %><</a></h2>
                <p>
                	Vietpro Academy thành lập năm 2009. Chúng tôi đào tạo chuyên sâu trong 2 lĩnh vực là Lập trình Website & Mobile nhằm cung cấp cho thị trường CNTT Việt Nam những lập trình viên thực sự chất lượng, có khả năng làm việc độc lập, cũng như Team Work ở mọi môi trường đòi hỏi sự chuyên nghiệp cao. 
                </p>
            </div>
            <div id="address" class="col-lg-3 col-md-6 col-sm-12">
            	<h3>Địa chỉ</h3>
                <p>B8A Võ Văn Dũng - Hoàng Cầu Đống Đa - Hà Nội</p>
                <p>Số 25 Ngõ 178/71 - Tây Sơn Đống Đa - Hà Nội</p>
            </div>
            <div id="service" class="col-lg-3 col-md-6 col-sm-12">
            	<h3>Dịch vụ</h3>
            	<p>Bảo hành rơi vỡ, ngấm nước Care Diamond</p>
            	<p>Bảo hành Care X60 rơi vỡ ngấm nước vẫn Đổi mới</p>
            </div>
            <div id="hotline" class="col-lg-3 col-md-6 col-sm-12">
            	<h3>Hotline</h3>
            	<p>Phone Sale: (+84) 0988 550 553</p>
                <p>Email: vietpro.edu.vn@gmail.com</p>
            </div>
        </div>
    </div>
</div>

<!--	Footer	-->
<div id="footer-bottom">
	<div class="container">
    	<div class="row">
        	<div class="col-lg-12 col-md-12 col-sm-12">
            	<p>
                    2018 © Vietpro Academy. All rights reserved. Developed by Vietpro Software.
                </p>
            </div>
        </div>
    </div>
</div>
<!--	End Footer	-->

app/views/client/_header.html.erb
<div id="header">
	<div class="container">
    	<div class="row">
        	<div id="logo" class="col-lg-3 col-md-3 col-sm-12">
            	<h1><%=link_to root_url do %> <%= image_tag "logo.png" %> <%end%> </h1>
            </div>
            <div id="search" class="col-lg-6 col-md-6 col-sm-12">
                <%= form_tag(search_path) do %>
                 <%= search_field_tag :search , params[:search] , placeholder: "Search" %>
                 <%= button_tag "Tìm Kiếm", :class => 'btn btn-danger' ,:name => nil%>  
              <% end %>
            </div>
            <div id="cart" class="col-lg-3 col-md-3 col-sm-12">
                <%= render 'carts/cart' %>
            </div>
        </div>
    </div>
    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler navbar-light" type="button" data-toggle="collapse" data-target="#menu">
    	<span class="navbar-toggler-icon"></span>
    </button>
</div>

app/views/client/_product.html.erb
<div class="product-item ">
    <a href="#"><%= image_tag product.prd_img %></a>
    <h4><%= link_to product.prd_name , root_url %></h4>
    <p>Giá Bán: <span><%= product.prd_price %></span></p>
</div>

app/views/client/_sidebar.html.erb
<div id="sidebar main-2" class="col-lg-4 col-md-12 col-sm-12">
    <div id="banner">
        <div class="banner-item">
            <a href="#"><%= image_tag "banner-1.png" , class: ""  %></a>
        </div>
        <div class="banner-item">
            <a href="#"><%= image_tag "banner-2.png" , class: ""  %></a>
        </div>
        <div class="banner-item">
            <a href="#"><%= image_tag "banner-3.png" , class: ""  %></a>
        </div>
        <div class="banner-item">
            <a href="#"><%= image_tag "banner-4.png" , class: ""  %></a>
        </div>
        <div class="banner-item">
            <a href="#"><%= image_tag "banner-5.png" , class: ""  %></a>
        </div>
        <div class="banner-item">
            <a href="#"><%= image_tag "banner-6.png" , class: ""  %></a>
        </div>
    </div>
</div>

app/views/client/_slider.html.erb
<div id="slide">
    <!-- The slideshow -->
    <div class="">
      <div class="">
        <%= image_tag "slide-1.png" %>
      </div>
      
    </div>
  </div>
  <!--	End Slider	-->

app/views/client/category.html.erb
<%= render "client/header" %>
<div id="body">
	<div class="container">
        <%= render "client/categories" %>
        <div class="row">
        	<div id="main" class="col-lg-8 col-md-12 col-sm-12">
                <div class="main-1">
                    <%= render "client/slider" %>


                    <h3><%= @category.name %>( có <%= @products.length%> sản phẩm )</h3>
                <div class="products">
                    <% @products.each do |product| %>
                    <div class="product-item ">
                        <a href="#"><%= image_tag product.prd_img %></a>
                        <h4><%= link_to product.prd_name , details_path(product.id) %></h4>
                        <p>Giá Bán: <span><%= product.prd_price.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %>d</span></p>
                    </div>
                       
                    <%end%>
                </div>
                <!--	End Feature Product	-->
                
                
                </div>
                

                <%= render "client/sidebar" %>


            </div>
        </div>

    </div>
</div>
<%= render "client/footer" %>

app/views/client/details.html.erb
<%= render "client/header" %>
<!--	End Header	-->

<!--	Body	-->
<div id="body">
	<div class="container">
    	<%= render "client/categories" %>
        <div class="row">
        	<div id="main" class="col-lg-8 col-md-12 col-sm-12">
            	
                <!--	End Slider	-->
                
                <!--	List Product	-->
                <div id="product">
                	<div id="product-head" class="row">
                    	<div id="product-img" class="col-lg-6 col-md-6 col-sm-12">
                        	<%= image_tag @product.prd_img %>
                        </div>
                        <div id="product-details" class="col-lg-6 col-md-6 col-sm-12">
                        	<h1><%= @product.prd_name %></h1>
                            <ul>
                            	<li><span>Bảo hành:</span> 12 Tháng</li>
                                <li><span>Đi kèm:</span> <%= @product.prd_accessories %></li>
                                <li><span>Tình trạng:</span> Máy Mới 100%</li>
                                <li><span>Khuyến Mại:</span> Dán Màn Hình 3 lớp</li>
                                <li id="price">Giá Bán (chưa bao gồm VAT)</li>
                                <li id="price-number"><%= @product.prd_price.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %>đ</li>
                                <li id="status"><%= @product.prd_status == true ? "Còn Hàng" : "Hết Hàng" %></li>
                            </ul>
                            
                            <%= form_for @order_item , remote:true do |f| %>
                                <%= f.hidden_field :product_id , :value => @product.id %>
                                <%= f.submit "Mua Ngay" , class:"btn btn-danger" %>
                            <%end%>
                        </div>
                    </div>
                    <div id="product-body" class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <h3>Đánh giá về <%= @product.prd_name %></h3>
                            <p>
                                <%= @product.prd_details %>
                            </p>
                            
                        </div>
                    </div>
                    
                    <!--	Comment	-->
                    <div id="comment" class="row">
                        <div class="col-lg-12 col-md-12 col-sm-12">
                            <h3>Bình luận sản phẩm</h3>
                            <% flash.each do |message_type, message| %>
                                    <div class="alert alert-<%= message_type %>"><%= message %></div>
                                <% end %>
                            <%= form_for @comment do |f| %>
                                <%= render 'shared/comment_error'%>
                                <%= f.label :product_id, @product.id , class: "hidden-shit"%>
                                <%= f.number_field :product_id , :value => @product.id , class: "hidden-shit"  %>
                                <%= f.label :name %>
                                <%= f.text_field :name, class: 'form-control' %>

                                <%= f.label :mail %>
                                <%= f.email_field :mail, class: 'form-control' %>

                                <%= f.label :details %>
                                <%= f.text_field :details, class: 'form-control' %>

                                
                                <%= f.submit "Gửi", class: "btn btn-primary" %>
                            <% end %>
                            
                        </div>
                    </div>
                    <!--	End Comment	-->  
                    
                    <!--	Comments List	-->
                    <div id="comments-list" class="row">
                    	<div class="col-lg-12 col-md-12 col-sm-12">
                            <% @comments.each do |comment| %>
                            <div class="comment-item">
                                <ul>
                                    <li><b><%= comment.name %></b></li>
                                    <li><%= comment.created_at %></li>
                                    <li>
                                        <p><%= comment.details%></p>
                                    </li>
                                </ul>
                            </div>
                            <% end %>

                        </div>
                    </div>
                    <!--	End Comments List	-->
                </div>
                <!--	End Product	--> 
                            
            </div>
            
           <%= render "client/sidebar" %>
        </div>
    </div>
</div>
<!--	End Body	-->

<%= render "client/footer" %>

app/views/client/index.html.erb
<%= render "client/header" %>
<div id="body">
	<div class="container">
        <%= render "client/categories" %>
        <div class="row">
        	<div id="main" class="col-lg-8 col-md-12 col-sm-12">
                <div class="main-1">
                    <%= render "client/slider" %>


                    <h3>Sản phẩm nổi bật</h3>
                    <div class="products">
                        <% @products1.each do |product1| %>
                        <div class="product-item ">
                            <a href="#"><%= image_tag product1.prd_img %></a>
                            <h4><%= link_to product1.prd_name , details_path(product1.id) %></h4>
                            <p>Giá Bán: <span><%= product1.prd_price.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %>d</span></p>
                        </div>
                        
                        <%end%>
                    </div>
                <!--	End Feature Product	-->
                
                    <h3>Sản phẩm mới</h3>
                <!--	Latest Product	-->
                    <div class="products">
                    
                            <% @products2.each do |product2| %>

                                <div class="product-item ">
                                    <a href="#"><%= image_tag product2.prd_img %></a>
                                    <h4><%= link_to product2.prd_name , root_url %></h4>
                                    <p>Giá Bán: <span><%= product2.prd_price.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse  %>d</span></p>
                                </div>
                                
                            <%end%>
                        
                        
                    </div>
                    
                </div>
                

                <%= render "client/sidebar" %>


            </div>
        </div>

    </div>
</div>
<%= render "client/footer" %>

app/views/client/search.html.erb
<%= render "client/header" %>
<div id="body">
	<div class="container">
        <%= render "client/categories" %>
        <div class="row">
        	<div id="main" class="col-lg-8 col-md-12 col-sm-12">
                <div class="main-1">
                    <%= render "client/slider" %>


                <div id="search-result">Kết quả tìm kiếm với sản phẩm <span><%= @parameter%></span></div>
                <div class="products">
                    <% @products.each do |product| %>
                    <div class="product-item ">
                        <a href="#"><%= image_tag product.prd_img %></a>
                        <h4><%= link_to product.prd_name , details_path(product.id) %></h4>
                        <p>Giá Bán: <span><%= product.prd_price.to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse %>d</span></p>
                    </div>
                       
                    <%end%>
                </div>
                <!--	End Feature Product	-->
                
                
                </div>
                

                <%= render "client/sidebar" %>


            </div>
        </div>

    </div>
</div>
<%= render "client/footer" %>