config/routes.rb
Rails.application.routes.draw do
  get 'order_items/create'
  get 'order_items/destroy'
  get 'order_items/update'
  get 'carts/show'
  root "client#index"
  get "login" => "sessions#new"
  get "signup" => "users#new"
  get "admin" => "users#index"
  post   'login'   => 'sessions#create'
  post 'comments' => "client#comment"  
  delete 'logout'  => 'sessions#destroy'
  get "search" => "client#search" , as: 'search'
  post "search" => "client#search" 
  get "products" => "products#index"
  get "details/:id" => "client#details" , as: "details"
  get "category/:id" => "client#category" , as: "category"
  resources :users
  resources :products
  resources :categories
  get "cart" => "carts#show"
  resources :order_items
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @categories = Category.all
    @order_items = current_order.order_items
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_cart.html.erb
<h5 class="cart-show" ><%= link_to "Giỏ Hàng : " , cart_path%><%= "#{current_order.order_items.size}"%></h5>

app/views/carts/_cart_item.html.erb
<%= render "client/header" %>
<div id="body">
	<div class="container">
        <%= render "client/categories" %>
        <div class="row">
        	<div id="main" class="col-lg-8 col-md-12 col-sm-12">
                <div class="main-1">
                    <%= render "client/slider" %>


                    <div id="my-cart">
                        <div class="row">
                            <div class="cart-nav-item col-lg-7 col-md-7 col-sm-12">Thông tin sản phẩm</div> 
                            <div class="cart-nav-item col-lg-2 col-md-2 col-sm-12">Tùy chọn</div> 
                            <div class="cart-nav-item col-lg-3 col-md-3 col-sm-12">Giá</div>    
                        </div>  
                        <% @order_items.each do |item| %>
                        <div class="cart-item row">
                            <div class="cart-thumb col-lg-7 col-md-7 col-sm-12">
                                <%= image_tag item.product.prd_img %>
                                <h4><%= item.product.prd_name %></h4>
                            </div> 
                            <%= form_for item , remote: true do |f| %>
                            <div class="cart-quantity col-lg-2 col-md-2 col-sm-12">
                                
                                    <%= f.hidden_field :product_id, :value => item.product.id %>
                                    
                                
                            </div> 
                            <div class="cart-price col-lg-3 col-md-3 col-sm-12"><b><%= item.total %>đ</b><%= link_to "Xóa" , order_item_path(item) , method: :delete , remote: true , class: "btn btn-danger"%></div>  
                            <% end %>  
                        </div>  
                        <%end%>
                        <h1>Tổng Số Tiền : <%= current_order.subtotal  %></h1>
                                   
                    </div>
                    <!--	End Cart	-->
                    
                    <!--	Customer Info	-->
                    <div id="customer">
                        <form method="post">
                        <div class="row">
                            
                            <div id="customer-name" class="col-lg-4 col-md-4 col-sm-12">
                                <input placeholder="Họ và tên (bắt buộc)" type="text" name="name" class="form-control" required>
                            </div>
                            <div id="customer-phone" class="col-lg-4 col-md-4 col-sm-12">
                                <input placeholder="Số điện thoại (bắt buộc)" type="text" name="phone" class="form-control" required>
                            </div>
                            <div id="customer-mail" class="col-lg-4 col-md-4 col-sm-12">
                                <input placeholder="Email (bắt buộc)" type="text" name="mail" class="form-control" required>
                            </div>
                            <div id="customer-add" class="col-lg-12 col-md-12 col-sm-12">
                                <input placeholder="Địa chỉ nhà riêng hoặc cơ quan (bắt buộc)" type="text" name="add" class="form-control" required>
                            </div>
                            
                        </div>
                        </form>
                        <div class="row">
                            <div class="by-now col-lg-6 col-md-6 col-sm-12">
                                <a href="#">
                                    <b>Mua ngay</b>
                                    <span>Giao hàng tận nơi siêu tốc</span>
                                </a>
                            </div>
                            <div class="by-now col-lg-6 col-md-6 col-sm-12">
                                <a href="#">
                                    <b>Trả góp Online</b>
                                    <span>Vui lòng call (+84) 0988 550 553</span>
                                </a>
                            </div>
                        </div>
                    </div>
                <!--	End Feature Product	-->
                
                
                </div>
                

                <%= render "client/sidebar" %>


            </div>
        </div>

    </div>
</div>
<%= render "client/footer" %>

app/views/carts/show.html.erb
<div id="card_item">
    <%= render "carts/cart_item" %>
</div>